language: node_js
services:
- redis-server
node_js:
- node
before_script:
- npm install -g gulp-cli gulp
script:
- gulp
- zip -r -q latest *
- mkdir -p upload
- mv latest.zip upload/latest.zip
env:
  global:
  - secure: cRxxf58a+RIORFglAJXK4BM6ZbaR5o5oamg1s5j/8HoeW2QZ3BVjUEh++AKuEF6VszWaKx2cTOkgm94jFCs/Cv3WDlXNe31VW02M0wpMyFPvx3a4G4ra3DM4L4k1EUXQiZzLJI2M/nN0HIUW73OObSLNQHWIYleiWnK5v4IMe0ZR5/pHD4y6SMowbukyVrUGEeFz4duKl/NRV0n4+71TphvBoR43tAWB6Hm+5Eyrw9gaymlUrZT7njG69nt07hg8EH23rfViX6sxxju0AwfGO6bXZrCBDETjDWy0zxADyyDqO1KVino2XCmRhRFQvjdbVuE59kBkSTCpPFVrealTd7oTHf28CBy5UryLdv3eww/XhNS2WVIEev2WD1WQ1vlMkbjbbFuvoNr8K90ADtnkpo3Fxkjjcr1QRW6ii4dEHQrMIyCQ6zgq9eE7jIspKjdGaXks0ikSRX4iQCNsxPfzAtsWt7dzJ0KCMAW9YKQV9yJkzdAt2E8J4Ikdq8T1Yjmwb4tVVwFEGQW2tvlCotSt7jelNydah1S9CPa8zsFY+nww0JgIvrN0G7T5vaVSPlZLjo7uaiLfPxWVAScUJmiZi0RedCUNOFU2NWQn7KPFiT453OBdFmOXgDqdva97N3vOYxW1oO4D9e8+kRxWZMq5FzW8FWUEXW9T0qw59LEOcFY=
  - secure: b7wlF2d2ixqlIAMzNUFujTQcLRc8Fdwc7CVaWxK5FahWRoeVJ+q+NGpZ8J74AwwN0jfFbiSP3zkgTXdQMEBE7Ru6oeo/tAZFtd/MDGwvT1JCWq8xS77KxiShbR/cY7ZPJ6YtMOnimmA5KsXaL3d6bxAxN5yRMex4TE89uL7AlPsENpiareqW+AzEgPPkDvB8MLw04R9qhMzJaQpTp2mf2b39hlSu0UNPYj/LsDVpIdpx6oQi3SGJ+b7yvwK6bQ2Ne0NvVoTIMaNzjx6NqlvynbObQa9Xt/iTT2thDoWs90SJeZQ/3qWx+HAu66xh0zxG0lalKOQQF3NTk8q3nAOKBRHF+wqdZdhpHE4qkIdLwyRHl4TkOPtANnpHCOl6NHtrfOBVrtbQNsraqeH+HlB6vQEHQY3hr+ibB89NAX08TZrIRHoM27+dIPZackg2slb9Pon8DxMtkOi1sKgNurbhDCrff+/5XMvJZVL9wuMkWPwaS1ZID9ZsyZsVlgB61eLdkbvExiTFNCC7y2EK6G/WHSqq29M/vx0pXGzlkU6+IT5fT5zYVTrAmBx5zYVAZUGgzDhSSZ988/tHhe6U8sROfmvsImHrqNSNfZnqJMLeeIRGuJ+HKZb3d84CmVD6+DRwKdShV5uxKmGEQj0jAGzDLeKZQvA2lsxtirrbaCjQwVY=
  - secure: Wb3ozX+GXhFUfpklY7tp/s5S72hRk3rET1pG+FKYd28S6vIH204KgUWxslXBlaGByAxZpbN0kQJflKYTEkMm7Vh0Nocf/4HJEJDLJm/TnMi9NMr3SYtRgUbbTikGIhua176CvXjBu7NgiiFXHmdFETBw5KRa79zElhyndpLHYodRKKwActQWd8lh7g0dksifB8oQbE53Y05ZZNn7oBjKTsmOJyRtDEf0Wo7N0Pg1lKOq5ekEa9i00bfZX2RJGB6hyziD0ZZutScRrCY3AqWmEf5YW2cvcPomrOSd05DzXlGnzGuavQqF6jFLJgSyjRavJUoy4vJbSXpzq50NaDt18iCpjH4qnb9lxBOHH2azljLmbJCC3fGnkTHvjnmahCQ1N5yxZCHmNqDuP5fia7ojLBkTsMAyrRtddHOuyVR/BPCwzNm+JIla/Bguc08LVbvhuF3Nu7Rth/A1Jha4q9cOP2fevtJDbtQT/Q0hETLT4S3UbjcfCGaMgjfMeFQUi13mbccKy8diXseKUt7CfR3Io3UiY2SPaL9GeLJRZkw0WuP5owwBJ2oN9tvTueRm5k1apW6rR78pM0M2FltQ2vrCneCFxCOi3b8jqhk6ICu5VWLLlI/eUlAc3KbHLgRK8/ghUiB6YV78SJ5Td8X45thO7jhz/D8oeZ8tFyjnMJXVtww=
deploy:
  matrix:
  - provider: s3
    bucket: codedeploy-website-api
    local_dir: upload
    upload-dir: prod
    on:
      branch: master
  - provider: s3
    bucket: codedeploy-website-api
    local_dir: upload
    upload-dir: dev
    on:
      branch: develop
  secret_access_key:
    secure: 82/uxWXT9MMFGTvCK5tVViM4JGhJX/Gt+TW7z47SzbZmngOpeIRAqt3+THooOv/hvB+v5mC16EgNL4Y5QapTLnrqsTe+/YK9Sgo6XKCRz0j7spZW/rB3l5F5kNg1jWmfqHMqrMIZLvwX3DSL5ltpcAETdtOfUaTuPSh/BGzdY2DC1PglJBVwZhI5keua5fPsNHcgZPMweejvl3lriCC/JKh5dP22RBrYtbIeNHsFnfSilc7MPpi02WzrztKoOjJnpG/aIhocjwVKHDHyBf8jiXCKJpqLLOTlV5LryBVN0Tdh7vZ2+5QN1Bn4UZXbJMkybS1kAGXFQgy4NH5RuZAdsl/z5gDV/fb2h0si85z3ixL/c4yPSKM+NnoZvdfG2g1MbtY1716iacNrFFV4x+km5To2TCsGfggJQRtMmHUuUX2FqB+igLosisetLuP5qmbaeZ1jkC3DgEV481OH+cWYoQfIIQ/j4xd3zdruM3cKPCyTn6+Emm8KR1shQAZd5hvjYWgOCMc5rInj0jj3tPJ9TZdHdJNDzzlWzWaMXcmDrPmLK6GrT5My2h00qgeE3WqXBBJh3ixvLG7dNym2GblqSOBCYoSxYiP2wERKmgWCJIguvcLbYE1PLq08NR6PHqvHdK0aSyeY5zv3COgiQME+Q4G45cJ5hn1DO0EAtZ2QCho=
  access_key_id:
    secure: y2cckqCKxy0TT4pih8ZGpJC43Ia6CW0F6zAfOO/31jRb+ypAwt5nLPDi4/a7W1GWLJ545fnbKpHRbS2QUYiGM2cwau2Eiy5A4opW3vK+WZo2vD+XGT07r9wf6tkCqiroZkX9Jk/KIBXZTIzEbhQFYQz2Fbcn5VRV6wNqUVjHvWLH50xlQDhk0VrcesDnZyzbqQ4z2GVY/qQ6yw0V+d4bwPF2BMT09QWrdyRpix6Vbr8PKN2oCTkVmzTfPuQJMChN1X876RzIfyTpgCdoGhVfoTwmrB5A3tbDA9iC9HWs+38C7eFj4sulMUjZk7RAWFbWtHLyj4YWRKaRZ9s0dwQaL7zn0VluCC/aMT0eQsAJA5u7SGeiNaY25APHdsVucQ5Tww6N5y4TcpKY6ZNPkUKwRHZDAMjVrwvWuvx/jY36cEtxGyHtlt6ETd4/a12NyrAByLL5N8y5OLMyV9mXeZHHdVmnzyAKnb/paD2uZhY8TYKdAy+pjCerLcSBBx602q0mHZ+LAdKJws/WFhWjIJWRwrlUroosWyZj09ijIRg9wNuhBzEMk77Tx2ReS3pAwxemRJ9HnTzyS159BOgjvx2g54Cxz/La+ByGI7kv/ehI9X/7gY4N6X02o5P4P4N9qFNid3WtUxbNPaPLhtZJlQA4HPh6FnHamo4fkbVBmRXyOYU=
